### PR TITLE
Add rainbow-delimiters faces

### PR DESCRIPTION
**Pull request by alternateved**
Hello, I would like to add faces for [rainbow-delimiters](https://github.com/Fanael/rainbow-delimiters). Thank you.

Best wishes,
alternateved

### CODE REVIEW

**Comment by motform** [comment]
Hi!

I had completely forgotten about rainbow-delimiters, thank you for adding them! At first I thought it was a bit jarring with the alternating `,fg1`, but thinking more about it I think it is probably the correct choice. After all, the point of rainbow-delimiters is to contrast/allow you do quickly disambiguate levels, and that contrast does that (arguably better than the stock set of colors of similar intensity).

**Comment by alternateved** [comment]
I tried a couple of variants and at the same time, trying to stay true to the theme and the best solution I could found is this alternating. Using other colors would either result in parentheses blending together with highlight face or with them being just unreadable.

**Comment by motform** [comment]
Oh yeah, I did not even consider the highlight face interaction, that would be super important. Great thinking!

**Comment by motform** [comment]
@slotThe 

Thank you for catching that, it was indeed a mistake! I was experimenting a bit for my own sake and accidentally committed it. I still think your version is the best execution of the intention of `rainbow-parens`, so I have now reverted that change. Apologies if it cause inconvenience!

**Pull request merged**
