### PR TITLE
Add support for `diredfl`

### PR DESCRIPTION
**Pull request by slotThe**
`Diredfl` adds extra faces and font-lock rules for `dired`.  Now, I know how "extra faces" sounds with regards to this theme, but hear me out!  It's really quite neat to be able to tell, at a glance, the difference between a symlink, directory, or "ordinary" file.  In that vein I've decided to highlight the file extension as well.

As always, any comments/suggestions are most welcome!

##### Before

2022-05-05-204124_1132x313_scrot

##### After

2022-05-05-204207_1133x389_scrot

In case you prefer non-highlighted extensions:

2022-05-05-204056_1129x262_scrot

### CODE REVIEW

**Comment by motform** [comment]
Wow, the original version of `diredfl` looks like an old DOS nightmare, well done on cleaning it up! I really like your highlight of the file extension, I think it is a nice way to provide "icon like" functionally and aid scanning.

One thing I thought about was that it might be nice to have the mode string font locked in like a string, as done in magit,
, might add a nice visual break since the column has a fixed width. There is a risk that it might float together with the heading, so one would have to to try that. 

Otherwise, great and really appreciated work as always!

**Comment by slotThe** [comment]
Thanks for the feedback!

> One thing I thought about was that it might be nice to have the mode string font locked in like a string, as done in magit, [magit-screenshot], might add a nice visual break since the column has a fixed width. There is a risk that it might float together with the heading, so one would have to to try that.

It does flow together with the heading a little, but that's certainly fixable.  The bigger problem is that there is no face for the absence of the directory indicator `d`[^1] and so it looks really irregular (at least to my eyes):

2022-05-06-191209_728x209_scrot

Not sure if this bothers you as much as it bothers me; if not I can certainly add this in (with some twiddling of the shades for the heading)!

[^1]: All othes instances of a `-` (for rwx) use `diredfl-no-priv` so this may well be a bug that's worth reporting upstream.  EDIT: https://github.com/purcell/diredfl/issues/15 let's see what happens

**Comment by motform** [comment]
You are totally right, the absence of `d` is really unsettling (in one of the strangest recorded uses of that word). I think the first version is the way to go!

**Comment by slotThe** [comment]
@motform upstream already merged the changes!  Should I play around with this a bit?

**Comment by motform** [comment]
Cool, well done! In that case, I think it would be nice to give it at try and move it a bit in line with `magit`, if that feels "right". Then again, it might conceptually be closer to your great treatment of `notmuch` and `message-mode`, as a reference of how tabular metadata should "feel".

**Pull request merged**
